releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-modeling}{bert-large-inference}'
slice_sets:
  bert-large-inference:
  - add_to_name: -bert-large-inference
    args:
    - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
    - PACKAGE_NAME=bert-large-inference
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/docker.md
        - name: Advanced Options
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/advancedoptions.md
        - name: License
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: intel/language-modeling:tf-latest-bert-large-inference
          <mode>: inference
          <model name>: BERT Large
          <use case>: language_modeling
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu
      - docs:
        - name: Title
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <fp32 precision>: FP32
          <fp32 advanced readme link>: fp32/Advanced.md
          <bfloat16 precision>: BFloat16
          <bfloat16 advanced readme link>: bfloat16/Advanced.md
          <model name>: BERT Large
          <use case>: language_modeling
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/bert-large-fp32-inference-tensorflow-container.html
        uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        - name: Model args
          uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/fp32/.docs/advanced/model_args.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: BERT Large
          <precision>: FP32
          <use case>: language_modeling
          <docker image>: 'intel/intel-optimized-tensorflow:tf-r2.5-icx-b631821f'
        uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/fp32
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/bfloat16/.docs/advanced/launch_benchmark_instructions.md
        - name: Model args
          uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/bfloat16/.docs/advanced/model_args.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: BERT Large
          <precision>: BFloat16
          <use case>: language_modeling
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/language_modeling/tensorflow/bert_large/inference/bfloat16 
    downloads:
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/fp32_bert_squad.pb
        destination: pretrained_model/fp32_bert_squad.pb
      - source : https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/optimized_bf16_bert.pb
        destination: pretrained_model/optimized_bf16_bert.pb
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6_1/bert_large_checkpoints.zip
        destination: pretrained_model/bert_large_checkpoints.zip
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/inference/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/inference/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/inference
      source: benchmarks/language_modeling/tensorflow/bert_large/inference
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_modeling/tensorflow/bert_large/inference
      source: models/language_modeling/tensorflow/bert_large/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_modeling/tensorflow/bert_large/inference/cpu
    partials:
    - unzip
    - tcmalloc
    - model_package
    - entrypoint
