releases:
    versioned:
        tag_specs:
            - "{_TAG_PREFIX}{intel-tf}{language-modeling}{mpi-horovod}{bert-large-training}"
slice_sets:
    bert-large-training:
        - add_to_name: "-bert-large-training"
          dockerfile_subdirectory: "model_containers"
          partials:
              - python-build
              - model_package
              - entrypoint
          documentation:
            - name: README.md
              uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <use case>: language_modeling
                <docker image>: intel/language-modeling:tf-latest-bert-large-training
              docs:
                - name: Title
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/title.md
                - name: Description
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/description.md
                - name: Datasets
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/datasets.md
                - name: Quick Start Scripts
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/quickstart.md
                - name: Docker
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/docker.md
                - name: Advanced Options
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/advancedoptions.md
                - name: License link
                  uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/license.md
            - docs:
              - name: Title
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/title.md
              - name: Description
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/description.md
              - name: Datasets
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/datasets.md
              - name: Quick Start Scripts
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/quickstart.md
              - name: Bare Metal
                uri: models/quickstart/language_modeling/tensorflow/bert_large/training/cpu/.docs/baremetal.md
              - name: Resources
                uri: models/quickstart/common/.docs/resources_with_portal_link.md
              name: README.md
              text_replace:
                <mode>: training
                <fp32 precision>: FP32
                <fp32 advanced readme link>: fp32/Advanced.md
                <bfloat16 precision>: BFloat16
                <bfloat16 advanced readme link>: bfloat16/Advanced.md
                <model name>: BERT Large
                <use case>: language_modeling
                <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/bert-large-fp32-training-tensorflow-container.html
              uri: models/benchmarks/language_modeling/tensorflow/bert_large/training
            - docs:
              - name: Title
                uri: models/quickstart/common/.docs/advanced/title.md
              - name: Description
                uri: models/quickstart/common/.docs/advanced/description.md
              - name: Setup
                uri: models/quickstart/common/.docs/advanced/setup.md
              - name: Docker arg
                uri: models/quickstart/common/.docs/advanced/docker_arg.md
              - name: Launch benchmark instructions
                uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/fp32/.docs/advanced/launch_benchmark_instructions.md
              name: Advanced.md
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <precision>: FP32
                <use case>: language_modeling
                <docker image>: 'intel/intel-optimized-tensorflow:latest'
              uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/fp32
            - docs:
              - name: Title
                uri: models/quickstart/common/.docs/advanced/title.md
              - name: Description
                uri: models/quickstart/common/.docs/advanced/description.md
              - name: Setup
                uri: models/quickstart/common/.docs/advanced/setup.md
              - name: Docker arg
                uri: models/quickstart/common/.docs/advanced/docker_arg.md
              - name: Launch benchmark instructions
                uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/advanced/launch_benchmark_instructions.md
              name: Advanced.md
              text_replace:
                <mode>: training
                <model name>: BERT Large
                <precision>: Bfloat16
                <use case>: language_modeling
                <docker image>: 'intel/intel-optimized-tensorflow:latest'
              uri: models/benchmarks/language_modeling/tensorflow/bert_large/training/bfloat16
          args:
              - PACKAGE_NAME=bert-large-training
          downloads:
          - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6_1/bert_large_checkpoints.zip
            destination: pretrained_model/bert_large_checkpoints.zip
          files:
              - source: benchmarks/common
                destination: benchmarks/common
              - source: benchmarks/launch_benchmark.py
                destination: benchmarks/launch_benchmark.py
              - source: benchmarks/language_modeling/tensorflow/bert_large
                destination: benchmarks/language_modeling/tensorflow/bert_large
              - source: models/language_modeling/tensorflow/bert_large/training
                destination: ./models/language_modeling/tensorflow/bert_large/training
              - source: quickstart/language_modeling/tensorflow/bert_large/training/cpu
                destination: quickstart
              - source: quickstart/common
                destination: quickstart/common
