releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{recommendation}{dien-training}'
slice_sets:
  dien-training:
  - add_to_name: -dien-training
    args:
    - PACKAGE_NAME=dien-training
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/docker_spr.md
        - name: License
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: intel/image-recognition:tf-latest-dien-training
          <mode>: training
          <model name>: DIEN
          <use case>: recommendation
        uri: models/quickstart/recommendation/tensorflow/dien/training/cpu
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/quickstart.md
        - name: BARE METAL
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: training
          <model name>: DIEN
          <use case>: recommendation
        uri: models/benchmarks/recommendation/tensorflow/dien/training
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/recommendation/__init__.py
      source: benchmarks/recommendation/__init__.py
    - destination: benchmarks/recommendation/tensorflow/__init__.py
      source: benchmarks/recommendation/tensorflow/__init__.py
    - destination: benchmarks/recommendation/tensorflow/dien/__init__.py
      source: benchmarks/recommendation/tensorflow/dien/__init__.py
    - destination: benchmarks/recommendation/tensorflow/dien/training/__init__.py
      source: benchmarks/recommendation/tensorflow/dien/training/__init__.py
    - destination: benchmarks/recommendation/tensorflow/dien/training
      source: benchmarks/recommendation/tensorflow/dien/training
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/recommendation/tensorflow/dien/training
      source: models/recommendation/tensorflow/dien/training
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/recommendation/tensorflow/dien/training/cpu 
