releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{mlperf-gnmt-inference}'
slice_sets:
  mlperf-gnmt-inference:
  - add_to_name: -mlperf-gnmt-inference
    args:
    - PACKAGE_NAME=mlperf-gnmt-inference
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/docker.md
        - name: License
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: 'intel/language-translation:tf-latest-mlperf-gnmt-inference'
          <mode>: inference
          <model name>: MLPerf GNMT
          <use case>: language_translation
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu
      - docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: MLPerf GNMT
          <fp32 precision>: FP32
          <fp32 advanced readme link>: fp32/Advanced.md
          <use case>: language_translation
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/gnmt-fp32-inference-tensorflow-container.html
        uri: models/benchmarks/language_translation/tensorflow/mlperf_gnmt/inference
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: MLPerf GNMT
          <package dir>: mlperf-gnmt-fp32-inference
          <precision>: FP32
          <use case>: language_translation
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/fp32
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/mlperf_gnmt_fp32_pretrained_model.pb
      destination: mlperf_gnmt_fp32_pretrained_model.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/__init__.py
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/__init__.py
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/mlperf_gnmt
      source: models/language_translation/tensorflow/mlperf_gnmt
    - destination: models/language_translation/tensorflow/mlperf_gnmt/gnmt-v0.5.2.patch
      source: models/language_translation/tensorflow/mlperf_gnmt/gnmt-v0.5.2.patch
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/mlperf_gnmt/inference/cpu
    partials:
    - model_package
    - language_translation/mlperf_gnmt_tf_addons
    - entrypoint
