releases:
  versioned:
    is_dockerfiles: true
    tag_specs:
    - '{nightly-tf-tfx-cpu}'

slice_sets:
    nightly-tf-tfx-cpu:
        - add_to_name: "nightly-tf-tfx-cpu"
          dockerfile_exclusive_name: "nightly-tf-tfx-cpu"
          dockerfile_subdirectory: "tfx"
          partials:
               - tensorflow/google-tensorflow-base
               - python3-pip
               - tensorflow/uninstall-google-tensorflow
               - tensorflow/tfx-install
               - tensorflow/nightly-tf-cpu
               - tensorflow/dependencies-for-tfx-examples
