releases:
  versioned:
    is_dockerfiles: true
    tag_specs:
    - '{nightly-tf-tfx-cuda}'

slice_sets:
    nightly-tf-tfx-cuda:
        - add_to_name: "nightly-tf-tfx-cuda"
          dockerfile_exclusive_name: "nightly-tf-tfx-cuda"
          dockerfile_subdirectory: "tfx"
          partials:
               - tensorflow/google-tensorflow-base
               - python3-pip
               - tensorflow/uninstall-google-tensorflow
               - tensorflow/tfx-install
               - tensorflow/nightly-tf-cuda
               - tensorflow/dependencies-for-tfx-examples
