releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{object-detection}{rfcn-inference}'
slice_sets:
  rfcn-inference:
  - add_to_name: -rfcn-inference
    args:
    - PACKAGE_NAME=rfcn-inference
    - TF_MODELS_BRANCH=6c21084503b27a9ab118e1db25f79957d5ef540b
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/docker.md
        - name: License
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: intel/object-detection:tf-latest-rfcn-inference
          <mode>: inference
          <model name>: RFCN
          <use case>: object_detection
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu
      - docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/object_detection/tensorflow/rfcn/inference/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <fp32 precision>: FP32
          <fp32 advanced readme link>: fp32/Advanced.md
          <int8 precision>: Int8
          <int8 advanced readme link>: int8/Advanced.md
          <model name>: RFCN
          <use case>: object_detection
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/rfcn-fp32-inference-tensorflow-container.html
        uri: models/benchmarks/object_detection/tensorflow/rfcn/inference
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/object_detection/tensorflow/rfcn/inference/int8/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <model name>: RFCN
          <precision>: Int8
          <mode>: inference
          <use case>: object_detection
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/object_detection/tensorflow/rfcn/inference/int8
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/object_detection/tensorflow/rfcn/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <model name>: RFCN
          <precision>: FP32
          <mode>: inference
          <use case>: object_detection
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/object_detection/tensorflow/rfcn/inference/fp32
    downloads:
    - destination: final_fused_pad_and_conv.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/rfcn_final_fused_pad_and_conv.pb
    - destination: frozen_inference_graph.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/rfcn_frozen_inference_graph.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/object_detection/__init__.py
      source: benchmarks/object_detection/__init__.py
    - destination: benchmarks/object_detection/tensorflow/__init__.py
      source: benchmarks/object_detection/tensorflow/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/__init__.py
      source: benchmarks/object_detection/tensorflow/rfcn/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/inference/__init__.py
      source: benchmarks/object_detection/tensorflow/rfcn/inference/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/inference
      source: benchmarks/object_detection/tensorflow/rfcn/inference
    - destination: models/common
      source: models/common
    - destination: models/object_detection/tensorflow/rfcn/inference
      source: models/object_detection/tensorflow/rfcn/inference
    - destination: models/object_detection/tensorflow/rfcn/inference/tf-2.0.patch
      source: models/object_detection/tensorflow/rfcn/inference/tf-2.0.patch
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/object_detection/tensorflow/rfcn/inference/cpu
    partials:
    - tcmalloc
    - model_package
    - object_detection/rfcn_patch
    - tar
    - entrypoint
