releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{recommendation}{wide-deep-inference}'
slice_sets:
  wide-deep-inference:
  - add_to_name: -wide-deep-inference
    args:
    - FETCH_PR=pull/7461/head:wide-deep-tf2
    - TF_MODELS_BRANCH=wide-deep-tf2
    - PACKAGE_NAME=wide-deep-inference
    dockerfile_subdirectory: model_containers
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6/wide_deep_fp32_pretrained_model.tar.gz
      destination: pretrained_model/wide_deep_fp32_pretrained_model.tar.gz
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/recommendation/__init__.py
      source: benchmarks/recommendation/__init__.py
    - destination: benchmarks/recommendation/tensorflow/__init__.py
      source: benchmarks/recommendation/tensorflow/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep/__init__.py
      source: benchmarks/recommendation/tensorflow/wide_deep/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep/inference/__init__.py
      source: benchmarks/recommendation/tensorflow/wide_deep/inference/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep/inference
      source: benchmarks/recommendation/tensorflow/wide_deep/inference
    - destination: models/common
      source: models/common
    - destination: models/recommendation/tensorflow/wide_deep/inference
      source: models/recommendation/tensorflow/wide_deep/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/recommendation/tensorflow/wide_deep/inference/cpu
    partials:
    - numactl
    - tensorflow/model-source
    - model_package
    - tar
    - entrypoint
    documentation:
      - name: README.md
        uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu
        text_replace:
          <mode>: inference
          <model name>: Wide & Deep
          <use case>: recommendation
          <docker image>: intel/recommendation:tf-latest-wide-deep-inference
        docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/docker.md
        - name: Advanced Options
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/advancedoptions.md
        - name: License link
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/license.md
      - name: README.md
        uri: models/benchmarks/recommendation/tensorflow/wide_deep/inference
        text_replace:
          <mode>: inference
          <fp32 precision>: FP32
          <fp32 advanced readme link>: fp32/Advanced.md
          <model name>: Wide & Deep
          <use case>: recommendation
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/wide-deep-fp32-inference-tensorflow-container.html
        docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/recommendation/tensorflow/wide_deep/inference/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/recommendation/tensorflow/wide_deep/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: Wide & Deep
          <precision>: FP32
          <use case>: recommendation
          <docker image>: intel/intel-optimized-tensorflow:latest
        uri: models/benchmarks/recommendation/tensorflow/wide_deep/inference/fp32
