releases:
  versioned:
    tag_specs:
    - '{pytorch-ipex-spr}'
slice_sets:
  pytorch-ipex-spr:
    - add_to_name: pytorch-ipex-spr
      dockerfile_subdirectory: pytorch
      args:
        - PYTORCH_WHEEL=torch-1.12.0a0+gitd2ae05f-cp37-cp37m-linux_x86_64.whl
        - IPEX_WHEEL=intel_extension_for_pytorch-1.12.0+cpu-cp37-cp37m-linux_x86_64.whl
        - PACKAGE_NAME=pytorch-ipex-spr
      partials:
        - centos8-base
        - unzip
        - pytorch/centos-intel-base-installs
        - pytorch/prep-conda-env
        - pytorch/install-pytorch-ipex-wheels
        - pytorch/jemalloc
        - pytorch/spr-base-release-conda-env
        - erase-openssl
      wrapper_package_files:
        - source: quickstart/spr_base/pytorch/build.sh
          destination: build.sh
        - source: dockerfiles/pytorch/pytorch-ipex-spr.Dockerfile
          destination: pytorch-ipex-spr.Dockerfile
        - source: tools/docker/whls
          destination: whls
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/spr_base/pytorch/README.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/spr_base/pytorch/.docs/title.md
          - name: Description
            uri: models/quickstart/spr_base/pytorch/.docs/description.md
          - name: Model Package
            uri: models/quickstart/spr_base/pytorch/.docs/container_package.md
          - name: Docker
            uri: models/quickstart/spr_base/pytorch/.docs/docker.md
          - name: License
            uri: models/quickstart/spr_base/pytorch/.docs/license.md
          name: README.md
          text_replace:
            <package name>: pytorch-ipex-spr.tar.gz
            <package dir>: pytorch-ipex-spr
            <docker image>: model-zoo:pytorch-ipex-spr
          uri: models/quickstart/spr_base/pytorch
