releases:
  versioned:
    tag_specs:
    - '{pytorch-multistage}{spr-bert-large-training}'
slice_sets:
  spr-bert-large-training:
    - add_to_name: -spr-bert-large-training
      dockerfile_subdirectory: pytorch
      args:
        - PYTORCH_IMAGE=model-zoo
        - PYTORCH_TAG=pytorch-ipex-spr
        - PACKAGE_NAME=pytorch-spr-bert-large-training
        - TRANSFORMERS_COMMIT=v4.18.0
      partials:
        - pytorch/gcc-and-utils
        - pytorch/tcmalloc
        - model_package
        - pytorch/models/bert-training-dependencies
        - pytorch/spr-release-conda-env
        - pytorch/spr-dnnl-max-var
        - pytorch/tcmalloc-entrypoint
      files:
        - source: models/language_modeling/pytorch/bert_large/training
          destination: models/language_modeling/pytorch/bert_large/training
        - source: quickstart/language_modeling/pytorch/bert_large/training/cpu/enable_optmization.diff
          destination: quickstart/enable_optmization.diff
        - source: quickstart/language_modeling/pytorch/bert_large/training/cpu/run_bert_pretrain_phase1.sh
          destination: quickstart/run_bert_pretrain_phase1.sh
        - source: quickstart/language_modeling/pytorch/bert_large/training/cpu/run_bert_pretrain_phase2.sh
          destination: quickstart/run_bert_pretrain_phase2.sh
      wrapper_package_files:
        - source: output/pytorch-spr-bert-large-training.tar.gz
          destination: model_packages/pytorch-spr-bert-large-training.tar.gz
        - source: quickstart/language_modeling/pytorch/bert_large/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/language_modeling/pytorch/bert_large/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/pytorch/pytorch-spr-bert-large-training.Dockerfile
          destination: pytorch-spr-bert-large-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: models/language_modeling/pytorch/bert_large/training/input_preprocessing
          destination: input_preprocessing
