releases:
  versioned:
    tag_specs:
    - '{pytorch-multistage}{spr-resnet50-training}'
slice_sets:
  spr-resnet50-training:
    - add_to_name: -spr-resnet50-training
      dockerfile_subdirectory: pytorch
      args:
        - PYTORCH_IMAGE=model-zoo
        - PYTORCH_TAG=pytorch-ipex-spr
        - PACKAGE_NAME=pytorch-spr-resnet50-training
        - TORCHVISION_VERSION=81fe60cc258f49ccfb0f9f32d78b4825754cff7b
      partials:
        - pytorch/gcc-and-utils
        - pytorch/torch-vision-from-source
        - pytorch/spr-model-installs
        - model_package
        - pytorch/spr-release-conda-env
        - pytorch/spr-dnnl-max-var
        - pytorch/jemalloc-libiomp5-entrypoint
      files:
        - source: models/image_recognition/pytorch/common
          destination: models/image_recognition/pytorch/common
        - source: quickstart/image_recognition/pytorch/resnet50/training/cpu/training.sh
          destination: quickstart/training.sh
      wrapper_package_files:
        - source: output/pytorch-spr-resnet50-training.tar.gz
          destination: model_packages/pytorch-spr-resnet50-training.tar.gz
        - source: quickstart/image_recognition/pytorch/resnet50/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/image_recognition/pytorch/resnet50/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/pytorch/pytorch-spr-resnet50-training.Dockerfile
          destination: pytorch-spr-resnet50-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party

