releases:
  versioned:
    tag_specs:
    - '{pytorch-multistage}{spr-dlrm-training}'
slice_sets:
  spr-dlrm-training:
    - add_to_name: -spr-dlrm-training
      dockerfile_subdirectory: pytorch
      args:
        - PYTORCH_IMAGE=model-zoo
        - PYTORCH_TAG=pytorch-ipex-spr
        - PACKAGE_NAME=pytorch-spr-dlrm-training
      partials:
        - pytorch/gcc-and-utils
        - pytorch/spr-model-installs
        - model_package
        - pytorch/models/dlrm-dependencies
        - pytorch/spr-release-conda-env
        - pytorch/spr-dnnl-max-var
        - pytorch/models/dlrm-jemalloc-entrypoint
      files:
        - source: models/recommendation/pytorch/dlrm
          destination: models/recommendation/pytorch/dlrm
        - source: quickstart/recommendation/pytorch/dlrm/training/cpu/training.sh
          destination: quickstart/training.sh
        - source: quickstart/recommendation/pytorch/dlrm/requirements.txt
          destination: quickstart/requirements.txt
      wrapper_package_files:
        - source: output/pytorch-spr-dlrm-training.tar.gz
          destination: model_packages/pytorch-spr-dlrm-training.tar.gz
        - source: quickstart/recommendation/pytorch/dlrm/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/recommendation/pytorch/dlrm/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/pytorch/pytorch-spr-dlrm-training.Dockerfile
          destination: pytorch-spr-dlrm-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
