releases:
  versioned:
    tag_specs:
    - '{pytorch-multistage}{spr-ssd-resnet34-inference}'
slice_sets:
  spr-ssd-resnet34-inference:
    - add_to_name: -spr-ssd-resnet34-inference
      dockerfile_subdirectory: pytorch
      args:
        - PYTORCH_IMAGE=model-zoo
        - PYTORCH_TAG=pytorch-ipex-spr
        - PACKAGE_NAME=pytorch-spr-ssd-resnet34-inference
        - TORCHVISION_VERSION=81fe60cc258f49ccfb0f9f32d78b4825754cff7b
      partials:
        - pytorch/gcc-and-utils
        - pytorch/torch-vision-from-source
        - pytorch/spr-model-installs
        - model_package
        - pytorch/spr-release-conda-env
        - pytorch/spr-dnnl-max-var
        - pytorch/jemalloc-libiomp5-entrypoint
      files:
        - source: models/object_detection/pytorch/ssd-resnet34/inference/cpu
          destination: models/object_detection/pytorch/ssd-resnet34/inference/cpu
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/inference_realtime.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/inference_throughput.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/accuracy.sh
          destination: quickstart/accuracy.sh
      wrapper_package_files:
        - source: output/pytorch-spr-ssd-resnet34-inference.tar.gz
          destination: model_packages/pytorch-spr-ssd-resnet34-inference.tar.gz
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/run.sh
          destination: run.sh
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/download_dataset.sh
          destination: download_dataset.sh
        - source: quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/download_model.sh
          destination: download_model.sh
        - source: dockerfiles/pytorch/pytorch-spr-ssd-resnet34-inference.Dockerfile
          destination: pytorch-spr-ssd-resnet34-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
