releases:
  versioned:
    is_dockerfiles: true
    tag_specs:
    - "{_TAG_PREFIX}{end2end-ubuntu}{weekly-ipex-dlsa}"
slice_sets:
  weekly-ipex-dlsa:
  - add_to_name: -weekly-ipex-dlsa
    dockerfile_subdirectory: "end2end"
    args:
        - PY_VERSION=3.7
        - IPEX_WHEEL_WW=08
        - IPEX_WHEEL_YEAR=2022
    partials:
        - end2end/dlsa-conda-env
        - end2end/profiling-transformers
        - end2end/pytorch-weekly-install
        - end2end/dlsa-conda-entrypoint
