releases:
  versioned:
    tag_specs:
    - '{pytorch-ipex-max-series-base-public}{pytorch-max-series-resnet50v1-5-inference}'
slice_sets:
  pytorch-max-series-resnet50v1-5-inference:
  - add_to_name: pytorch-max-series-resnet50v1-5-inference
    dockerfile_exclusive_name: -resnet50v1-5-inference
    args:
    - PACKAGE_NAME=pytorch-max-series-resnet50v1-5-inference
    dockerfile_subdirectory: gpu_model_containers
    downloads: []
    files:
    - source: quickstart/image_recognition/pytorch/resnet50v1_5/inference/gpu/README_Max_Series.md
      destination: README.md
    - destination: models/image_recognition/pytorch/resnet50v1_5/inference/gpu
      source: models/image_recognition/pytorch/resnet50v1_5/inference/gpu
    - destination: quickstart/inference_block_format.sh
      source: quickstart/image_recognition/pytorch/resnet50v1_5/inference/gpu/inference_block_format.sh
    wrapper_package_files:
     - source: quickstart/image_recognition/pytorch/resnet50v1_5/inference/gpu/build.sh
       destination: build.sh
     - source: dockerfiles/gpu_model_containers/pytorch-max-series-resnet50v1-5-inference.Dockerfile
       destination: pytorch-max-series-resnet50v1-5-inference.Dockerfile
     - source: output/pytorch-max-series-resnet50v1-5-inference.tar.gz
       destination: model_packages/pytorch-max-series-resnet50v1-5-inference.tar.gz
     - source: ""
       destination: info.txt
     - source: third_party
       destination: licenses/third_party
     - source: LICENSE
       destination: licenses/LICENSE
    partials:
    - model_package
    - entrypoint
