releases:
  versioned:
    tag_specs:
    - '{spr-bert-large-pretraining}'
slice_sets:
  spr-bert-large-pretraining:
    - add_to_name: tf-spr-bert-large-pretraining
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-bert-large-pretraining
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
        - PY_VERSION=3.8
      partials:
        - tensorflow/tensorflow-base
        - python-build
        - gcc-8
        - openmpi-4.1.0
        - openssh
        - horovod
        - model_package
        - numactl
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/language_modeling/__init__.py
          source: benchmarks/language_modeling/__init__.py
        - destination: benchmarks/language_modeling/tensorflow/__init__.py
          source: benchmarks/language_modeling/tensorflow/__init__.py
        - destination: benchmarks/language_modeling/tensorflow/bert_large/README.md
          source: benchmarks/language_modeling/tensorflow/bert_large/README.md
        - destination: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
          source: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
        - destination: benchmarks/language_modeling/tensorflow/bert_large/training
          source: benchmarks/language_modeling/tensorflow/bert_large/training
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/language_modeling/tensorflow/bert_large/training/cpu/pretraining.sh
          destination: quickstart/pretraining.sh
        - destination: models/common
          source: models/common
        - destination: models/language_modeling/tensorflow/bert_large/training
          source: models/language_modeling/tensorflow/bert_large/training
        - destination: quickstart/common
          source: quickstart/common
      wrapper_package_files:
        - source: output/tf-spr-bert-large-pretraining.tar.gz
          destination: model_packages/tf-spr-bert-large-pretraining.tar.gz
        - source: quickstart/language_modeling/tensorflow/bert_large/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/language_modeling/tensorflow/bert_large/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-bert-large-pretraining.Dockerfile
          destination: tf-spr-bert-large-pretraining.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
