releases:
  versioned:
    tag_specs:
    - '{spr-ssd-resnet34-training}'
slice_sets:
  spr-ssd-resnet34-training:
    - add_to_name: tf-spr-ssd-resnet34-training
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-ssd-resnet34-training
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
        - PY_VERSION=3.8
        - TF_MODELS_BRANCH=8110bb64ca63c48d0caee9d565e5b4274db2220a
        - TF_BENCHMARKS_BRANCH=509b9d288937216ca7069f31cfb22aaa7db6a4a7
      partials:
        - tensorflow/tensorflow-base
        - common
        - python-build
        - gcc-8
        - openmpi-4.1.0
        - openssh
        - horovod
        - opencv
        - numactl
        - tensorflow-addons-0.18.0
        - tensorflow/model-source
        - object_detection/protoc
        - object_detection/pip_installs
        - model_package
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/object_detection/__init__.py
          source: benchmarks/object_detection/__init__.py
        - destination: benchmarks/object_detection/tensorflow/__init__.py
          source: benchmarks/object_detection/tensorflow/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/training/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/training/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/training
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/training
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/training/cpu/training.sh
          destination: quickstart/training.sh
        - destination: models/common
          source: models/common
        - destination: models/object_detection/tensorflow/ssd-resnet34/training
          source: models/object_detection/tensorflow/ssd-resnet34/training
        - destination: models/object_detection/tensorflow/ssd-resnet34/training/__init__.py
          source: models/object_detection/tensorflow/ssd-resnet34/training/__init__.py
        - destination: quickstart/common
          source: quickstart/common
      wrapper_package_files:
        - source: output/tf-spr-ssd-resnet34-training.tar.gz
          destination: model_packages/tf-spr-ssd-resnet34-training.tar.gz
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-ssd-resnet34-training.Dockerfile
          destination: tf-spr-ssd-resnet34-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
