releases:
  versioned:
    tag_specs:
    - '{spr-transformer-mlperf-training}'
slice_sets:
  spr-transformer-mlperf-training:
    - add_to_name: tf-spr-transformer-mlperf-training
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-transformer-mlperf-training
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
      partials:
        - tensorflow/tensorflow-base
        - python-build
        - gcc-8
        - openmpi-4.1.0
        - openssh
        - horovod
        - model_package
        - numactl
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/language_translation/__init__.py
          source: benchmarks/language_translation/__init__.py
        - destination: benchmarks/language_translation/tensorflow/__init__.py
          source: benchmarks/language_translation/tensorflow/__init__.py
        - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
          source: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
        - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
          source: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
        - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training
          source: benchmarks/language_translation/tensorflow/transformer_mlperf/training
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - destination: models/common
          source: models/common
        - destination: models/language_translation/tensorflow/transformer_mlperf/training
          source: models/language_translation/tensorflow/transformer_mlperf/training
        - destination: quickstart/common
          source: quickstart/common
        - destination: quickstart/training.sh
          source: quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/training.sh
      wrapper_package_files:
        - source: output/tf-spr-transformer-mlperf-training.tar.gz
          destination: model_packages/tf-spr-transformer-mlperf-training.tar.gz
        - source: quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-transformer-mlperf-training.Dockerfile
          destination: tf-spr-transformer-mlperf-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
