releases:
  versioned:
    tag_specs:
    - '{spr-ssd-mobilenet-inference}'
slice_sets:
  spr-ssd-mobilenet-inference:
    - add_to_name: tf-spr-ssd-mobilenet-inference
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-ssd-mobilenet-inference
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
        - PY_VERSION=3.8
      partials:
        - tensorflow/tensorflow-base
        - model_package
        - common
        - python-build
        - tensorflow/model-source
        - object_detection/ssd-mobilenet/pip_installs
        - object_detection/protoc
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/object_detection/__init__.py
          source: benchmarks/object_detection/__init__.py
        - destination: benchmarks/object_detection/tensorflow/__init__.py
          source: benchmarks/object_detection/tensorflow/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/README.md
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/README.md
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/inference_realtime_multi_instance.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/inference_throughput_multi_instance.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/accuracy.sh
          destination: quickstart/accuracy.sh
        - destination: models/common
          source: models/common
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference
          source: models/object_detection/tensorflow/ssd-mobilenet/inference
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
        - destination: quickstart/common
          source: quickstart/common
      downloads:
        - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/ssdmobilenet_fp32_pretrained_model_combinedNMS.pb
          destination: pretrained_model/ssdmobilenet_fp32_pretrained_model_combinedNMS.pb
        - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/ssdmobilenet_int8_pretrained_model_combinedNMS_s8.pb
          destination: pretrained_model/ssdmobilenet_int8_pretrained_model_combinedNMS_s8.pb
      wrapper_package_files:
        - source: output/tf-spr-ssd-mobilenet-inference.tar.gz
          destination: model_packages/tf-spr-ssd-mobilenet-inference.tar.gz
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-ssd-mobilenet-inference.Dockerfile
          destination: tf-spr-ssd-mobilenet-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/README_SPR.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/title.md
          - name: Description
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/description.md
          - name: Model Package
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/wrapper_package.md
          - name: Quickstart
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/quickstart.md
          - name: Datasets
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/datasets.md
          - name: Container build
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/container_build.md
          - name: Docker
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/docker_spr.md
          - name: License
            uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/.docs/license.md
          name: README_SPR.md
          text_replace:
            <model name>: SSD-MobileNet
            <mode>: inference
            <package name>: tf-spr-ssd-mobilenet-inference.tar.gz
            <package dir>: tf-spr-ssd-mobilenet-inference
            <docker image>: model-zoo:tf-spr-ssd-mobilenet-inference
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu
