releases:
  versioned:
    tag_specs:
    - '{spr-resnet50v1-5-inference}'
slice_sets:
  spr-resnet50v1-5-inference:
    - add_to_name: tf-spr-resnet50v1-5-inference
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-resnet50v1-5-inference
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
      partials:
        - tensorflow/tensorflow-base
        - model_package
        - numactl
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/image_recognition/__init__.py
          source: benchmarks/image_recognition/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/__init__.py
          source: benchmarks/image_recognition/tensorflow/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/__init__.py
          source: benchmarks/image_recognition/tensorflow/resnet50v1_5/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/__init__.py
          source: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference
          source: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/inference_realtime_weightsharing.sh
          destination: quickstart/inference_realtime_weightsharing.sh
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/inference_realtime_multi_instance.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/inference_throughput_multi_instance.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/accuracy.sh
          destination: quickstart/accuracy.sh
        - destination: models/common
          source: models/common
        - destination: models/image_recognition/tensorflow/resnet50v1_5
          source: models/image_recognition/tensorflow/resnet50v1_5
        - destination: quickstart/common
          source: quickstart/common
      downloads:
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_8/bias_resnet50.pb
        destination: pretrained_model/bias_resnet50.pb
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_8/bf16_resnet50_v1.pb
        destination: pretrained_model/bf16_resnet50_v1.pb
      - source: https://zenodo.org/record/2535873/files/resnet50_v1.pb
        destination: pretrained_model/resnet50_v1.pb
      wrapper_package_files:
        - source: output/tf-spr-resnet50v1-5-inference.tar.gz
          destination: model_packages/tf-spr-resnet50v1-5-inference.tar.gz
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-resnet50v1-5-inference.Dockerfile
          destination: tf-spr-resnet50v1-5-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party

