releases:
  versioned:
    tag_specs:
    - '{spr-dien-training}'
slice_sets:
  spr-dien-training:
  - add_to_name: tf-spr-dien-training
    args:
    - PACKAGE_NAME=tf-spr-dien-training
    dockerfile_subdirectory: tensorflow-spr
    args:
      - PACKAGE_NAME=tf-spr-dien-training
      - TENSORFLOW_IMAGE=model-zoo
      - TENSORFLOW_TAG=tensorflow-spr
    partials:
      - tensorflow/tensorflow-base
      - model_package
      - numactl
      - gcc-8
      - openmpi-4.1.0
      - openssh
      - entrypoint
    wrapper_package_files:
        - source: output/tf-spr-dien-training.tar.gz
          destination: model_packages/tf-spr-dien-training.tar.gz
        - source: quickstart/recommendation/tensorflow/dien/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/recommendation/tensorflow/dien/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-dien-training.Dockerfile
          destination: tf-spr-dien-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
    files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/recommendation/__init__.py
          source: benchmarks/recommendation/__init__.py
        - destination: benchmarks/recommendation/tensorflow/__init__.py
          source: benchmarks/recommendation/tensorflow/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/__init__.py
          source: benchmarks/recommendation/tensorflow/dien/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/training/__init__.py
          source: benchmarks/recommendation/tensorflow/dien/training/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/training
          source: benchmarks/recommendation/tensorflow/dien/training
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - destination: models/common
          source: models/common
        - destination: models/recommendation/tensorflow/dien/training
          source: models/recommendation/tensorflow/dien/training
        - destination: quickstart/common
          source: quickstart/common
        - destination: quickstart/training.sh
          source: quickstart/recommendation/tensorflow/dien/training/cpu/training.sh
