releases:
  versioned:
    tag_specs:
    - '{tensorflow-spr-3dunet}'
slice_sets:
  tensorflow-spr-3dunet:
    - add_to_name: tensorflow-spr-3dunet
      dockerfile_subdirectory: tensorflow-spr
      args:
        - TENSORFLOW_WHEEL=tf_nightly-2.9.0.202212-cp38-cp38-linux_x86_64.whl
        - PACKAGE_NAME=tensorflow-spr-3dunet
      partials:
        - centos-stream8-base
        - tensorflow/spr-dnnl-max-var
        - tensorflow/spr-mkl-native-format-var
        - tensorflow/tf-spr-3dunet-whl
      files:
        - source: quickstart/spr_base/tensorflow/build_3dunet_base.sh
          destination: build.sh
        - source: dockerfiles/tensorflow-spr/tensorflow-spr-3dunet.Dockerfile
          destination: tensorflow-spr-3dunet.Dockerfile
        - source: tools/docker/whls
          destination: whls
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/spr_base/tensorflow/3dunet_base_README.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/spr_base/tensorflow/.docs/title.md
          - name: Description
            uri: models/quickstart/spr_base/tensorflow/.docs/description.md
          - name: Model Package
            uri: models/quickstart/spr_base/tensorflow/.docs/container_package.md
          - name: Docker
            uri: models/quickstart/spr_base/tensorflow/.docs/docker.md
          - name: License
            uri: models/quickstart/spr_base/tensorflow/.docs/license.md
          name: 3dunet_base_README.md
          text_replace:
            <package name>: tensorflow-spr-3dunet.tar.gz
            <package dir>: tensorflow-spr-3dunet
            <docker image>: model-zoo:tensorflow-spr-3dunet
            <wheel name>: "tf_nightly-2.9.0.202212-cp38-cp38-linux_x86_64.whl"
          uri: models/quickstart/spr_base/tensorflow
