releases:
  versioned:
    tag_specs:
    - '{tensorflow-spr}'
slice_sets:
  tensorflow-spr:
    - add_to_name: tensorflow-spr
      dockerfile_subdirectory: tensorflow-spr
      args:
        - TF_WHEEL=tf_nightly-2.10.0.202218-cp38-cp38-linux_x86_64.whl
        - TF_ESTIMATOR_VER=2.10.0.dev2022042008
        - KERAS_NIGHTLY_VER=2.10.0.dev2022042007
        - PACKAGE_NAME=tensorflow-spr
        - PY_VER=38
      partials:
        - centos8-base
        - tensorflow/spr-dnnl-max-var
        - tensorflow/spr-mkl-native-format-var
        - tensorflow/tf-installs
        - tcmalloc
        - erase-openssl
      files:
        - source: quickstart/spr_base/tensorflow/build.sh
          destination: build.sh
        - source: dockerfiles/tensorflow-spr/tensorflow-spr.Dockerfile
          destination: tensorflow-spr.Dockerfile
        - source: tools/docker/whls
          destination: whls
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/spr_base/tensorflow/README.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/spr_base/tensorflow/.docs/title.md
          - name: Description
            uri: models/quickstart/spr_base/tensorflow/.docs/description.md
          - name: Model Package
            uri: models/quickstart/spr_base/tensorflow/.docs/container_package.md
          - name: Docker
            uri: models/quickstart/spr_base/tensorflow/.docs/docker.md
          - name: License
            uri: models/quickstart/spr_base/tensorflow/.docs/license.md
          name: README.md
          text_replace:
            <package name>: tensorflow-spr.tar.gz
            <package dir>: tensorflow-spr
            <docker image>: model-zoo:tensorflow-spr
            <wheel name>: "tf_nightly-2.10.0.202218-cp38-cp38-linux_x86_64.whl"
          uri: models/quickstart/spr_base/tensorflow
